version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/calendar_db
      GOOGLE_CLIENT_ID: 522469680670-qnghrldoflld88lfh5i4injrqgurf3g2.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_REDIRECT_URI: http://localhost:4000/auth/google/callback
      PORT: 4000
    volumes:
      - ./server:/app
    command: sh -c "npx prisma migrate dev --name init && npx ts-node-dev src/index.ts"

volumes:
  pgdata: